Repository wildan3105/github-langs, pull requests merged in 2020-10, with the labels that each got.

#139 refactor: remove dotenv, use process.env instead for simplicity
  README.md
  lib/controller.js
  package.json
Labels: hacktoberfest

#143 feat: add pre-commit hook
  package-lock.json
  package.json
Labels: testing

#147 docs: update GitHub template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#160 cleanup: remove unused files
  .dockerignore
  Dockerfile
  README.md
  package-lock.json
  package.json
  resemblejscontainer.html
  screenshot.png
  start-xvfb.sh
Labels: refactor

#159 Add watcher gulp for compile scss
  gulpfile.js
  package-lock.json
  package.json
Labels: hacktoberfest-accepted

#167 [Refactor] Better codebase structure
  .eslintrc.json
  config/api_url.js
  config/constants.js
  config/error_messages.js
  config/random_statements.js
  gulpfile.js
  lib/controller.js
  lib/public/json/colors.json
  package.json
  public/css/base.scss
  public/css/screen/base.min.css
  public/css/themes/_dark.scss
  public/css/themes/_light.scss
  public/img/blue-check.png
  public/img/favicon.png
  public/img/forkme.png
  public/js/chart.js
  public/js/social.js
  public/js/spinner.js
  public/json/colors.json
  src/api/app.js
  src/api/controller.js
  src/api/routes.js
  src/api/service.js
  src/index.js
  src/pages/index.handlebars
  src/pages/layouts/main.handlebars
  src/pages/partials/404.handlebars
  src/pages/partials/body.handlebars
  src/pages/partials/footer.handlebars
  src/pages/partials/head.handlebars
  src/utils/emoji_generator.js
  src/utils/language_colors_generator.js
  tests/api/app.test.js
  tests/api/controller.test.js
  tests/api/routes.test.js
  tests/index.test.js
  tests/utils/chart.test.js
  tests/utils/emoji_generator.test.js
  tests/utils/language_colors_generator.test.js
  tests/utils/spinner.test.js
Labels: refactor
